### ISSUE TITLE
Router integration?

### ISSUE THREAD

**Issue by beatscode** [HuckRidge/hvue#1]
Just curious how would you go about integrating a vue-router?
https://github.com/vuejs/vue-router/blob/dev/examples/basic/app.js

**Comment by HuckRidgeSW** [comment]
@beatscode Sorry for the oh-so-late response.  I forgot to "watch" my own repository (:facepalm:)  and didn't get a notification of this issue, and it's been a while since I fiddled with it.  (Technically, I didn't realize I _had_ to watch _my own_ repository to get notifications about new issues.  Live and learn.  Again, though, sorry.)

You'd have to create a VueRouter object, probably with code similar to NewComponent in component.go, and add a

```
Router *js.Object `js:"router"`
```

slot to Config in option.go, and then write a function similar to `func Template(template string) ComponentOption` to set the Router slot.

This kind of highlights a drawback of the static-ness of the approach I've taken, in that you need to modify the definition of `Config`, though _I think_ everything else could be added without modifying the core library.

**Comment by HuckRidgeSW** [comment]
If you didn't sweat the `Config` object, then the Template-like function might look like this:

```go
func Router(router Router) ComponentOption {
	return func(c *Config) {
                 c.Object.Set("router", router.Object)
	}
}
```

**Comment by beatscode** [comment]
No worries, I'll try this out. Thanks for the reply

**Comment by HuckRidgeSW** [comment]
How goes it?  Have you had any luck with this approach?

**Comment by HuckRidgeSW** [comment]
Closing.  Please re-open if you have further questions or comments.
