### ISSUE TITLE
MDC

### ISSUE THREAD

**Issue by ghost** [HuckRidge/hvue#3]
This looks pretty nice. Even has proper examples.

I am wishing to build on top of this to add:

1. Vue MDC material design.

2. Hooks into server side reactive system using graphql.

3. Might save the view model / aggregates in a gophers sqllite db inside the browser.

This would make a decent application framework in golang and still be pretty easy for non hardcore golang people to extend to GUI and maybe the backend with enough smart codegen.

If you happen to know if a good vuejs material design this would get the balls rolling. I saw a few around but figured I could ask you first.

If you want an explanation of how I am hooking graphql and reactive backend in let me know. It means the GUI updates whenever someone else fires a mutation without doing anything at all to the GUI.

Anyway hope to hear back from you.

Oh and I decided to not use vecty for now until it stabilises and is WASM ready. Can't afford to boil the ocean in that area as don't have endless time.

**Comment by theclapp** [comment]
> This looks pretty nice. Even has proper examples.

Thanks!

> I am wishing to build on top of this to add: [... stuff ...]

Sounds neat.

> If you happen to know if a good vuejs material design this would get the balls rolling.

I'm afraid I don't.  I didn't even know what "vuejs material design" meant till I [Googled it](https://www.google.com/search?q=vuejs+materials+design).  https://vuematerial.io/ looks handy, as do several other results in that search.

If you're not familiar with it, there's [a Vue.js newsletter](https://www.getrevue.co/profile/vuenewsletter?utm_campaign=Issue&utm_content=forwarded&utm_medium=email&utm_source=Vue.js+News).  (Actually I think there are several, but that's the one I subscribe to.)

> If you want an explanation of how I am hooking graphql and reactive backend in let me know. It means the GUI updates whenever someone else fires a mutation without doing anything at all to the GUI.

Yes, I'd like to hear more.  (It wouldn't have to be here, necessarily, though that'd be fine.  A blog (or anywhere else) would be fine.)

> Oh and I decided to not use vecty for now until it stabilises and is WASM ready. Can't afford to boil the ocean in that area as don't have endless time.

Whaaat?  Inconceivable!

Thanks again for trying hvue.

**Comment by HuckRidgeSW** [comment]
> This looks pretty nice. Even has proper examples.

Thanks!

> I am wishing to build on top of this to add: [... stuff ...]

Sounds neat.

> If you happen to know if a good vuejs material design this would get the balls rolling.

I'm afraid I don't.  I didn't even know what "vuejs material design" meant till I [Googled it](https://www.google.com/search?q=vuejs+materials+design).  https://vuematerial.io/ looks handy, as do several other results in that search.

If you're not familiar with it, there's [a Vue.js newsletter](https://www.getrevue.co/profile/vuenewsletter?utm_campaign=Issue&utm_content=forwarded&utm_medium=email&utm_source=Vue.js+News).  (Actually I think there are several, but that's the one I subscribe to.)

> If you want an explanation of how I am hooking graphql and reactive backend in let me know. It means the GUI updates whenever someone else fires a mutation without doing anything at all to the GUI.

Yes, I'd like to hear more.  (It wouldn't have to be here, necessarily, though that'd be fine.  A blog (or anywhere else) would be fine.)

> Oh and I decided to not use vecty for now until it stabilises and is WASM ready. Can't afford to boil the ocean in that area as don't have endless time.

Whaaat?  Inconceivable!

Thanks again for trying hvue.

**Comment by nikolay-turpitko** [comment]
@gedw99 

Hi there,

I use this MDC lib: https://github.com/matsp/material-components-vue, and would recommend it. At least it mostly suits my (quite simple) needs. The lib is a bit raw, but guy, who maintain it, is friendly and helped me to fix several issues I found and submitted. Also, this lib itself is a thin wrapper around more mature and "more official" lib: https://github.com/material-components/material-components-web. Both have quite lean documentation, which can be both pro and con. What I like the most, that I was able to eliminate usage of NPM, webpack etc. (using jsdelivr combine: https://www.jsdelivr.com/features). Probably, other libs would allow it too, but looking at their docs, I would suspect they are heavily coupled to specific tool chain (may be it's a wrong impression, I'm not that much into JS world).

My prototype is not publicly available and is quite simple (app bar + drawer + fab button + some content). I guess I would extract some parts, suitable to be shared, but I'm not sure this worth the trouble - they are simple indeed and would just reiterate samples already existed in this project (which I used myself to learn how to implement my prototype). Most difficult part (at least for me) is JS<->Go type conversion of complex types (when having "js" tag on the struct is not enough). Once you have it, all other thing are straightforward. I did it manually. May be something like https://godoc.org/github.com/shurcooL/go/gopherjs_http/jsutil#Wrap would simplify it a bit more (just guess, haven't checked it yet). `NewT` is not very helpful for this case.

So, I guess there is some room for improvement at the type conversion (which, probably, should be addressed at gopherjs level and contribute to all bindings and similar projects), otherwise I don't see much things to improve on the MDC<->hvue boundary. It's quite straightforward already (in my opinion). Can't say about your other 2 bullet points.

**Comment by ghost** [comment]
I also have been using those 2 vuejs libs.
I also prefer the one your using though, so we can work together to bring it up to quality if you want.

Regarding the is types.
I codegen every viewmodel the client needs from the server event sourcing architecture.
This removes 100% of any "flux " code from the client and makes everything much simpler.

The server side event sourcing system creates an aggregate and then pushes any change to all clients via NATS. So every client is always up to date and if one goes offline it will catch-up when it comes back online. This is the core of how graphql works essentially. I am crushed for time and will link to the code if you want it for sure .
What are you doing server side ?

**Comment by nikolay-turpitko** [comment]
@gedw99 

At server side I have JSON API, created with https://echo.labstack.com/ lib, nothing fancy. It's just a prototype yet, as I said. I'm assessing alternatives. I'm not convinced yet, that Go/GopherJS is a good match there (in my project) at all. It brings some level of boilerplate code and quite a huge script blob (runtime), which is roughly the same size as all the rest of other JS libs. It adds ~50% to the load time. And, honestly, it doesn't add much value to the customer product (yep, I have more fun developing it, but this is hard to sell to the customer). I anticipated that this combination would make me more productive, but (at least at the moment) it turned out that bottleneck just moved from the JS part to connection between JS and Go. Not between server and client. This is simple - because I can use Go on both sides and `encoding/json` + `net/http` (or derivatives) on both sides I just reuse Go model types (I use conditional compilation tags to avoid compiling other Go code by gopherjs). So, I marshal/unmarshal Go structs on both sides with helpers and that's it. I don't use any code generation here, don't think I can gain much from it. Though, it's mostly because server API is not formally defined (I mean like with swagger etc). Otherwise I, probably, would. I'd appreciate if you could add a link to your code, it sounds it more sophisticated and may be it'd be useful for other users of `hvue` too. But I think you've misunderstood me, when I complained about additional level of boilerplate on the JS<->Go boundary, I told not about server to client side, it's on the client side between Go and JS type system. Like converting relatively complex Go struct into JS object and back. Let's say I use `vue-good-table`, and it takes a rows object. Row can contain fields of different types (for instance date/time). VueJS has two-way binding of this object, which would nicely work with simple JSON. But it's not work as nice with Go structs. I have to convert dates with additional code, introduce js.Object field etc. May be I can simplify it a bit, will see, it's just a first prototype after all. And, probably, I won't go this path anyway, because of heavy runtime, I'm not sure yet.

Now I see that may be I misunderstood your first post. I thought you need some feedback on using `vuejs` MDC libs with `hvue`. My answer was that it's quite doable and not that difficult to justify introducing yet another layer of abstraction/complexity on top of `hvue`. But yeah, there are rough corners, and I pointed one, perceiving most sharp for me. From your answer I understood, that you, probably, much deeper see these matters, then I initially thought. It seems, I cannot add much more to this discussion. Cheers.

**Comment by ghost** [comment]
@nikolay-turpitko 

Ok i see where the pain is. The GOPHERJS <--> Pure js type conversions. Lets get realistic.
You must use Vue because it has MDC and works well.
You dont have to use gopherjs, but can code in just JS. 
But you want to code gen the golang Structs to the JS.

I would use this but thats me. You will get huge speed up too.
full example:
https://github.com/improbable-eng/grpc-web/tree/master/example

You should also not have your golang structs be the same schema as your Client structs directly. 
SO the GRPC is structured to how the Client wants the data shaped ! THen on the server you just deconstruct the data and do the CRUD with your DB

that will do it  in your use case :) I know you will disagree because life is not that simple but anyway :)

**Comment by ghost** [comment]
typescript support is good
https://vuejs.org/v2/guide/typescript.html

not sure about MDC layer though ?
https://github.com/matsp/material-components-vue/issues/136

**Comment by ghost** [comment]
Also if you DO want to keep the gopherjs just use this:
https://github.com/johanbrandhorst/grpcweb-example

same as the other one but instead of Typescript its gopherjs in the client.

**Comment by ghost** [comment]
https://github.com/b3ntly/vue-grpc

**Comment by ghost** [comment]
@nikolay-turpitko not sure i addresses your area of interest at all. trying to..
anyway, i am mostly going to try to get MDC workng with this for now.

**Comment by HuckRidgeSW** [comment]
This conversation seems to've run its course.  Closing issue.  Please re-open if you'd like to continue discussing material design.
